spring:
  application:
    name: learn-jpa-querydsl
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa-querydsl?characterEncoding=UTF-8&useSSL=false
    username: querydsl
    password: 123456
  jpa:
    show-sql: true